--- 
stages: 
  - name: Build
    inputs: 
      - type: git
        branch: master
    triggers: 
      - type: commit
    jobs: 
      - name: Build
        type: builder
  - name: Deploy
    inputs: 
      - type: job
        stage: Build
        job: Build
    triggers: 
      - type: stage
    jobs: 
      - name: dev
        type: deployer
        script: |-
            #!/bin/bash -x
            CLOUDANT_NAME="node-red-shared-cloudant"
            cf push "${CF_APP}" --no-start
            cf set-env "${CF_APP}" NODE_RED_STORAGE_NAME "${CLOUDANT_NAME}"
            cf create-service cloudantNoSQLDB Lite "${CLOUDANT_NAME}"
            sleep 60
            cf bind-service "${CF_APP}" "${CLOUDANT_NAME}" -c '{"role":"Manager"}'

            # Start CF Application
            cf start "${CF_APP}"
            
            # Support Japanese HIRAGANA for kids
            cf "${CF_APP}" -c curl -L -O https://raw.githubusercontent.com/tjbotfan/tjbotzero-raspbian/master/messagecatalog_hiragana.zip
            cf "${CF_APP}" -c unzip messagecatalog_hiragana.zip
            cf "${CF_APP}" -c cp -r \@node-red/ /home/vcap/app/node_modules/node-red/node_modules/
            
            # View logs
            cf logs "${CF_APP}" --recent
            
            # test 
            ibmcloud resource service-instances
            
        target:
          region_id: ${CF_REGION_ID}
          organization: ${CF_ORGANIZATION}
          space: ${CF_SPACE}
          application: ${CF_APP}
          api_key: ${API_KEY}
